// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/cash.tsx";
import * as $2 from "./routes/defi.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/staking.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Header.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/cash.tsx": $1,
    "./routes/defi.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/staking.tsx": $4,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Header.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
